// <auto-generated />
using Bota.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bota.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210923231755_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Bota.Infrastructure.Models.BotConfig", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Prefix")
                        .HasColumnType("longtext");

                    b.Property<string>("SteamApiKey")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BotConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
