// <auto-generated />
using System;
using Bota.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bota.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210925134221_NewFields")]
    partial class NewFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Bota.Infrastructure.Models.BotConfig", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Prefix")
                        .HasColumnType("longtext");

                    b.Property<string>("SteamApiKey")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BotConfigs");

                    b.HasData(
                        new
                        {
                            Id = 889924246820749312ul,
                            Prefix = "/",
                            SteamApiKey = "00AF2C79D6E3395D77541A5E0C5377E4"
                        });
                });

            modelBuilder.Entity("Bota.Infrastructure.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("BotConfigId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("MessageText")
                        .HasColumnType("longtext");

                    b.Property<int?>("MessageTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BotConfigId");

                    b.HasIndex("MessageTypeId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Bota.Infrastructure.Models.MessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MessageType");
                });

            modelBuilder.Entity("Bota.Infrastructure.Models.Message", b =>
                {
                    b.HasOne("Bota.Infrastructure.Models.BotConfig", null)
                        .WithMany("Messages")
                        .HasForeignKey("BotConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bota.Infrastructure.Models.MessageType", "MessageType")
                        .WithMany()
                        .HasForeignKey("MessageTypeId");

                    b.Navigation("MessageType");
                });

            modelBuilder.Entity("Bota.Infrastructure.Models.BotConfig", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
